name: filterable_generator
description: "Geração automática de filtros e ordenações com source_gen."
version: 0.4.0
repository: https://github.com/SamuelGFDias/filterable
homepage: https://github.com/SamuelGFDias/filterable/tree/master/packages/filterable_generator
environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  # Use ranges amplos para garantir compatibilidade com riverpod, json_serializable, etc.
  analyzer: ">=7.0.0 <10.0.0" 
  source_gen: ">=3.0.0 <5.0.0"
  build: ">=3.0.0 <5.0.0"
  filterable_annotation: ^0.2.0
  # ou a versão: ^0.2.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
  build_test: ^3.0.0


topics:
  - filter
  - codegen
  - annotations

license: MIT