name: filterable_annotation
description: Annotations for automatic filter and sort generation with source_gen and build_runner. Build dynamic, type-safe filters for your Dart models.
version: 1.0.0
repository: https://github.com/SamuelGFDias/filterable
homepage: https://github.com/SamuelGFDias/filterable
documentation: https://github.com/SamuelGFDias/filterable/blob/main/README.md
issue_tracker: https://github.com/SamuelGFDias/filterable/issues

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

topics:
  - filter
  - sort
  - codegen
  - annotations
  - build-runner

funding:
  - https://github.com/sponsors/SamuelGFDias
